from backend.app.services.weather_service import get_district_weather, DISTRICT_COORDS
from backend.app.services.satellite_service import fetch_or_create_satellite_observations
from backend.app.services.sms_service import send_sms_advisory
